services:
- type: web
name: twilio-openai-realtime-poc
env: node
plan: free
autoDeploy: true
buildCommand: npm ci
startCommand: node server.js
healthCheckPath: /healthz
envVars:
- key: OPENAI_REALTIME_MODEL
value: gpt-4o-realtime-preview
